import Head from 'next/head';
import Link from 'next/link';

export default function App() {
  return (
    <div>
      <Head>
        <title>Motion</title>
        <meta name="description" content="Generated by" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="py-2 pb-4 text-black" style={{ marginTop: '-1rem' }}>
        <div className="max-w-7xl mx-auto px-4 flex items-center justify-between">
          <div>
            <img src="/MOTION_LOGO.png" alt="Motion Logo" className="h-88 w-288 m-10" />
          </div>
          <div className="flex items-center space-x-4">
          <Link href="/about">
            <span>About</span>
          </Link>
          <Link href="/contact">
            <span>Contact</span>
          </Link>
          <Link href="/dashboard">
            <span>Dashboard</span>
          </Link>
          <Link href="/login">
            <span>Login</span>
          </Link>
            <Link href="/get-motion">
              <button className="bg-black text-white py-2 px-4 rounded">Get Motion</button>
            </Link>
          </div>
        </div>
      </nav>
      <main className="container mx-auto mt-8">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold mb-4">Motion - where knowledge takes flight.</h1>
          <Link href="/get-started">
            <button className="bg-black text-white py-2 px-4 rounded">Get Started</button>
          </Link>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="bg-white shadow-md rounded-lg p-6">
            <img src="timer.png" alt="timer" className="w-full h-auto max-h-26 object-cover mb-2 rounded-lg" />
            <p className="text-gray-600">Timer - Manage your time effectively with our timer feature.</p>
          </div>
          <div className="bg-white shadow-md rounded-lg p-6">
            <img src="todo-list.png" alt="timer" className="w-full h-auto max-h-26 object-cover mb-2 rounded-lg" />
            <p className="text-gray-600">To Do List - Keep track of your tasks and stay organized.</p>
          </div>
          <div className="bg-white shadow-md rounded-lg p-6">
            <img src="whiteboard.png" alt="timer" className="w-full h-auto max-h-26 object-cover mb-2 rounded-lg" />
            <p className="text-gray-600">Whiteboard - Collaborate with others using our interactive whiteboard.</p>
          </div>
          <div className="bg-white shadow-md rounded-lg p-6">
            <img src="music.png" alt="timer" className="w-full h-auto max-h-26 object-cover mb-2 rounded-lg" />
            <p className="text-gray-600">Music - Relax and focus with our built-in music player.</p>
          </div>
        </div>
      </main>
    </div>
  );
}
